### ISSUE TITLE
Casting across R/W type parameters

### ISSUE THREAD

**Issue by aws-alepay** [rust-console/voladdress#21]
Hello! My team is using this crate to manage volatility for peripheral-device register control blocks at work. We have designed the following strategy:

```rust
#[repr(C)]
struct DeviceBlock {
  // fields (scalar and array) go here
}

impl DeviceBlock {
  fn get_field(this: VolAddress<Self, (), ()> -> VolAddress<Field, R, W> {
    this.cast::<u8>().add(BYTE_OFFSET).cast::<Field>()
  }
  // etc
}

impl DeviceBlock {
  fn manipulate_field(this: VolAddress<Self, (), ()>) {
    Self::get_field(this).read_or_write_or_apply();
  }
}
```

This allows us to separate the memory layout definitions, the register access permissions, and the register behaviors, so that each can be tracked individually and managed against the source documentation.

We use `(), ()` type parameters on `VolAddress<DeviceBlock>` to make it impossible to load or store the entire register suite, and then attach correct read or write permissions to each register field in the block according to the documentation. This is a fairly common pattern in complex MMIO devices: individual registers within a block may be read-only, write-only, read/write, or clear-on-write, in a heterogenous collection within a single context.

The `.cast()` method, of course, does not permit changing R/W permissions, so the pseudocode above is *actually* written as `NewPermission::new(old_permission.cast::<T>().add(offset).as_usize())`.

Would it be possible and/or desirable to attach methods for deliberate changing of the R/W permission types to give a semantic name to this sort of behavior?

**Comment by Lokathor** [comment]
Seems simple enough to add a `change_permissions` method. I'll try to do that later today.
