### ISSUE TITLE
`VolBlockIter::nth` implementaiton always skip one too many element

### ISSUE THREAD

**Issue by nicopap** [rust-console/voladdress#30]
current implementation is
```rust
  fn nth(&mut self, n: usize) -> Option<Self::Item> {
    if n < self.count {
      self.count -= n;
      self.base = unsafe { self.base.add(1 + n) };
      Some(self.base)
    } else {
      self.count = 0;
      None
    }
  }

```
However, to reflect the `next` implementation, it should be:
```rust
  fn nth(&mut self, n: usize) -> Option<Self::Item> {
    if n < self.count {
      self.count -= n;
      self.base = unsafe { self.base.add(n) };
      self.next()
    } else {
      self.count = 0;
      None
    }
  }

```

A good test case is `iter.nth(0)`, it should return the same value as if `iter.next()` was called, but with the current implementation, it returns one after the next.

Edit: also true of `nth_back`

**Comment by nicopap** [comment]
I guess this makes `nth` unsound as well. If you call multiple times `iter.nth(0)`, `self.count` is never updated, but `self.base` is incremented, and you could easily get out of bound and break the safety contract of `VolBlock`.

**Comment by Lokathor** [comment]
uggghhhh yeah you're right. i can fix it in a few.
